samples_manager/urls.py
from django.conf.urls import url, include

from django.views.generic import TemplateView
from . import views, user_views, experiment_views, sample_views, dosimeter_views, irradiation_views, compound_views



urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<experiment_id>[0-9]+)/experiment/$', experiment_views.experiment_details, name='experiment_details'),
    url(r'^logged_user/$',  user_views.view_user, name='view_user'),
    url(r'^experiments/$', experiment_views.experiments_list, name='experiments_list'),
    url(r'^user/(?P<pk>\d+)/experiments/$', experiment_views.admin_experiments_user_view, name='admin_experiments_user_view'),
    url(r'^admin/experiments/$', experiment_views.admin_experiments_list, name='admin_experiments_list'),
    url(r'^experiments/history/$', experiment_views.admin_experiments_list, name='experiments_history'),
    url(r'^experiment/new/$', experiment_views.experiment_new, name='experiment_new'),
    url(r'^experiments/(?P<pk>\d+)/update/$', experiment_views.experiment_update, name='experiment_update'),
    url(r'^experiments/(?P<pk>\d+)/delete/$', experiment_views.experiment_delete, name='experiment_delete'),
    url(r'^experiments/(?P<pk>\d+)/clone/$', experiment_views.experiment_clone, name='experiment_clone'),
    url(r'^experiments/(?P<pk>\d+)/validate/$', experiment_views.experiment_validate, name='experiment_validate'),
    url(r'^experiments/(?P<pk>\d+)/status/$', experiment_views.experiment_status_update, name='experiment_status_update'),
    url(r'^experiments/(?P<pk>\d+)/print/$', views.print_experiment_view, name='print_experiment_view'),
    url(r'^users/$',  user_views.users_list, name='users_list'),
    url(r'^experiment/(?P<experiment_id>\d+)/users/$',  user_views.experiment_users_list, name='experiment_users_list'),
    url(r'^experiment/(?P<experiment_id>\d+)/user/new/$',  user_views.user_new, name='user_new'),
    url(r'^user/new/$',  user_views.admin_user_new, name='admin_user_new'),
    url(r'^experiment/(?P<experiment_id>\d+)/user/(?P<pk>\d+)/update/$', user_views.user_update, name='user_update'),
    url(r'^experiment/(?P<experiment_id>\d+)/user/(?P<pk>\d+)/delete/$', user_views.user_delete_from_experiment, name='user_delete_from_experiment'),
    url(r'^user/(?P<pk>\d+)/delete/$', user_views.admin_user_delete, name='admin_user_delete'),
    url(r'^user/(?P<pk>\d+)/update/$', user_views.admin_user_update, name='admin_user_update'),
    url(r'^regulations/$',views.regulations, name='regulations'),
    url(r'^fluence_conversion/$',views.fluence_conversion, name='fluence_conversion'),
    url(r'^experiment/(?P<experiment_id>\d+)/samples/$', sample_views.experiment_samples_list, name='experiment_samples_list'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/new/$', sample_views.sample_new, name='sample_new'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/update/$', sample_views.sample_update, name='sample_update'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/clone/$', sample_views.sample_clone, name='sample_clone'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/delete/$', sample_views.sample_delete, name='sample_delete'),
    url(r'^experiment/(?P<experiment_id>\d+)/samples/move_samples/$', sample_views.move_samples, name='move_samples'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/print/label/$', views.print_sample_label_view, name='print_sample_label_view'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/print/$', views.print_sample_view, name='print_sample_view'),
    url(r'^dosimeters/$',  dosimeter_views.dosimeters_list, name='dosimeters_list'),
    url(r'^dosimeter/new/$',  dosimeter_views.dosimeter_new, name='dosimeter_new'),
    url(r'^dosimeter/(?P<pk>\d+)/update/$',  dosimeter_views.dosimeter_update, name='dosimeter_update'),
    url(r'^dosimeter/(?P<pk>\d+)/clone/$',  dosimeter_views.dosimeter_clone, name='dosimeter_clone'),
    url(r'^dosimeter/(?P<pk>\d+)/delete/$',  dosimeter_views.dosimeter_delete, name='dosimeter_delete'),
    url(r'^dosimeter/(?P<pk>\d+)/print/label/$', views.print_dosimeter_label_view, name='print_dosimeter_label_view'),
    url(r'^experiment/(?P<experiment_id>\d+)/dosimeter/assign/$', dosimeter_views.assign_dosimeters, name='assign_dosimeters'),
    url(r'^dosimeters/generate/ids/$', dosimeter_views.generate_dos_ids, name='generate_dos_ids'),
    url(r'^irradiations/$', irradiation_views.irradiations, name='irradiations'),
    url(r'^search_irradiations/$', views.search_irradiations, name='search_irradiations'),
    url(r'^search/experiment/(?P<experiment_id>\d+)/sample$', sample_views.search_samples, name='search_samples'),
    url(r'^search/experiments/user$', views.search_experiments_user, name='search_experiments_user'),
    url(r'^search/admin/experiments/$', views.search_experiments_admin, name='search_experiments_admin'),
    url(r'^search/experiment/(?P<experiment_id>\d+)/users/$', views.search_experiment_users, name='search_experiment_users'),
    url(r'^search/admin/users/$', views.search_users_admin, name='search_users_admin'),
    url(r'^search/dosimeters/$', views.search_dosimeters, name='search_dosimeters'),
    url(r'^admin/compound/new/$', compound_views.admin_compound_new, name='admin_compound_new'),
    url(r'^admin/compound/(?P<pk>\d+)/update/$', compound_views.admin_compound_update, name='admin_compound_update'),
    url(r'^admin/compound/(?P<pk>\d+)/delete/$', compound_views.admin_compound_delete, name='admin_compound_delete'),
    url(r'^experiment/(?P<experiment_id>\d+)/compound/new/$', compound_views.compound_new, name='compound_new'),
    url(r'^compounds/$', compound_views.compounds_list, name='compounds_list'),
    url(r'^experiment/(?P<experiment_id>\d+)/assign_set_ids/$', sample_views.assign_set_ids, name='assign_set_ids'),
    url(r'^experiment/(?P<experiment_id>\d+)/archive/samples/$', sample_views.archive_experiment_samples, name='archive_experiment_samples'),
    url(r'^experiment/(?P<experiment_id>\d+)/new/irradiation/$', irradiation_views.new_group_irradiation, name='new_group_irradiation'),
    url(r'^irradiation/new/$', irradiation_views.irradiation_new, name='irradiation_new'),
    url(r'^irradiation/(?P<pk>\d+)/update/$', irradiation_views.irradiation_update, name='irradiation_update'),
    url(r'^irradiation/(?P<pk>\d+)/delete/$', irradiation_views.irradiation_delete, name='irradiation_delete'),
    url(r'^irradiation/(?P<pk>\d+)/status/update/$', irradiation_views.irradiation_status_update, name='irradiation_status_update'),
    url(r'^register/preferences/$', views.register_preferences, name='register_preferences'),
    url(r'^change/experiment/(?P<pk>\d+)/visibility/$', experiment_views.change_experiment_visibility, name='change_experiment_visibility'),
    url(r'^change/experiment/(?P<pk>\d+)/visibility/on/$', experiment_views.change_experiment_visibility, name='change_experiment_visibility_on'),
    url(r'^change/experiment/(?P<pk>\d+)/visibility/off/$', experiment_views.change_experiment_visibility, name='change_experiment_visibility_off'),
    url(r'^get/sec/$', views.get_sec, name='get_sec'),
    url(r'^admin/dosimetry/results/$', irradiation_views.admin_dosimetry_results, name='admin_dosimetry_results'),
    url(r'^sample/(?P<sample_id>\d+)/dosimetry/results/$', irradiation_views.dosimetry_results, name='dosimetry_results'),
    url(r'^irradiation/beam/change/$', views.in_beam_change, name='in_beam_change'),
    url(r'^select_table/$', views.select_table, name='select_table'),
    url(r'^experiment/(?P<pk>\d+)/comment/$', experiment_views.experiment_comment_update, name='experiment_comment_update'),
    url(r'^read/(?P<pk>\d+)/trec$', views.read_sample_trec, name='read_sample_trec'),
    url(r'^samples/$',sample_views.admin_samples_list, name='admin_samples_list'),
    ]

test-irrad-management-page/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    # Examples:
    # url(r'^$', 'test2_samples_manager.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^samples_manager/', include('samples_manager.urls', namespace="samples_manager")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^terms_conditions/', TemplateView.as_view(template_name='terms_conditions.html'), name='terms_conditions'),
    url(r'^fluence_conversion/', TemplateView.as_view(template_name='fluence_conversion.html'), name='fluence_conversion'),
]

samples_manager/templates/base.html
<meta charset="UTF-8"> 
{% load staticfiles %}
<html>
    <head>
        <title>ITA Data Manager</title>
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.datetimepicker.css' %}"/>
        <link rel="stylesheet" type="text/css"  href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" type="text/css"  href="{% static 'css/ui/semantic.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/widget.css' %}">
        <link rel="stylesheet" type="text/css"  href="{% static 'css/cern_toolbar.css' %}">
        <link rel="stylesheet" type="text/css"  href="{% static 'css/number-polyfill.css' %}">
        <link rel="stylesheet" type="text/css"  type="text/css" href="{% static 'css/cookieconsent.min.css' %}"/>
        <link rel="stylesheet" type="text/css"  href="{% static 'css/style2.css' %}">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.8.0/spectrum.min.css">
        <script src="{% static 'js/cookieconsent.min.js' %}"></script>
    </head>
    <body id="home" class="pushable">
        <div class="pusher">
            <div class="page header">
                <div class="ui container">
                    <div id="ctl00_ctl00_pnlToolbar">
                        <div id="cern-toolbar">
                                <h1><a href="https://www.fnal.gov/" title="Fermilab">Fermi <span>National Accelerator Laboratory</span></a></h1>
                                <ul class="cern-signedin">
                                    <li class="cern-accountlinks"><a class="cern-account" href='{% url 'samples_manager:index' %}' title="Sign in to your CERN account">Sign in</a></li>
                                    <li><a class="cern-directory" href="https://www.fnal.gov/pub/resources/index.html" title="Browse Fermilab resources on the FNAL website">Resources</a></li>
                                </ul>
                        </div>
                    </div>
                    <div class="ui text menu">
                        <div class="item">
                                <a href="{% url 'samples_manager:index' %}" class="item">
                                <b>HOME</b>
                                </a>
                                <a href="{% url 'samples_manager:experiments_list' %}" class="item">
                                <b>EXPERIMENTS</b>
                                </a>
                                <a target='_blank' href="https://op-webtools.web.cern.ch/irrad/index.html#/" class="item">
                                <b>BPM</b>
                                </a>
                                <a target='_blank' href="https://ita.fnal.gov/" class="item">
                                <b>ITA</b>
                                </a>
                                <div class="ui dropdown link item allowed_dropdown">
                                    <span class="text"><b>INFO</b></span>
                                    <i class="dropdown icon"></i>
                                    <div class="menu">
                                        <a href="{% url 'terms_conditions' %}" class="item"><b>GENERAL TERMS</b></a>
                                        <a href="{% url 'fluence_conversion'%}"class="item"><b>FLUENCE CONVERSIONS</b></a>
                                    </div>
                                </div>
                        </div>
                        <div class = "ui right floated item">
                            <a href="https://ps-irrad.web.cern.ch/" class="ui small image">
                            <img src="{% static  'images/logo.png' %}"> 
                            </a>
                        </div>
                        <div class = "item">
                            <a href="http://aida2020.web.cern.ch/" class="ui small image">
                            <img src="{% static 'images/aida2020orange.png' %}"> 
                            </a>
                        </div>
                    </div>
                    <div class= "ui center aligned blue raised segment">
                        <h1 class="ui center aligned header">ITA Data Manager</h1>
                    </div>
                </div>
            </div>
        
            <div class="page content">
                <div class='ui container'>
                            {% block content %}
                            {% endblock %}
                </div>
            </div>
        </div>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> 
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="{% static 'js/custom_css.js' %}"></script>
        <script src="{% static 'js/samples.js' %}"></script>
        <script src="{% static 'js/experiments.js' %}"></script>
        <script src="{% static 'js/users.js' %}"></script>
        <script src="{% static 'js/dosimeters.js' %}"></script>
        <script src="{% static 'js/compounds.js' %}"></script>
        <script src="{% static 'js/irradiations.js' %}"></script>  
        <script src="{% static 'js/number-polyfill.js' %}"></script>
        <script src="{% static 'js/sorttable.js' %}"></script>
        <script src="{% static 'css/ui/semantic.min.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.8.0/spectrum.min.js"></script>
        <script src="{% static 'js/DYMO.Label.Framework.2.0.2.js' %}"></script>
        <script>
            $('.allowed_dropdown').dropdown();
            function goBack() {
                window.history.back();
            }
       </script>
        {% block javascript %}

        {% endblock %}

        </body>
    </html>

samples_manager/templates/fluence_conversion.html
{% extends 'base.html' %}
{% block content %}
<div class= "ui center aligned segment" id="main_panel">
  <h2>Fluence and Dose Conversions</h2>
</div>
<div class="ui horizontal segments">
    <div class="ui segment">
        <h3 class = "ui center aligned header">Proton vs. 1MeV neutron equivalent fluence</h3>
            <p style="text-align: justify">
                The equivalent 1 MeV neutron fluence Φ<sub>eq</sub> can be calculated multiplying the proton fluence (Φ<sub>p</sub>) by the hardness factor k: </p>
                <div class= "ui center aligned segment">
                    <p><bold>Φ<sub>eq</sub> = k ×  Φ<sub>p</sub> [cm<sup>-2</sup>] </bold></p>
                </div>
               <p style="text-align: justify"> For a 24 GeV/c proton beam (IRRAD) k = 0.58 (best estimate from experimental measurements: <a href="https://cds.cern.ch/record/2162852" style=" text-decoration: underline;"> https://cds.cern.ch/record/2162852 </a>
            </p>
    </div>
    <div class="ui segment">
         <h3 class = "ui center aligned header">Proton fluence vs. Total Ionising Dose</h3>
            <p style="text-align: justify">
                Proton of momentum 	&ge;GeV/c and pions &ge;300 MeV/c deposit energy at a rate of ~2 MeV·cm<sup>2</sup>/g in practically all target materials (minimum ionizing energy loss rate). Under these conditions (valid for the CERN PS protons of IRRAD and positive pions at PSI) a good estimation of the absorbed dose [Gy] can be done using: </p>
                <div class= "ui center aligned segment">
                    <p>Dose [Gy] = 1.602 × 10<sup>-10</sup> × (dE/dx)<sub>min</sub> [MeV·cm<sup>2</sup>/g] × Φ<sub>p</sub>[cm<sup>-2</sup>]</p>
                </div>
               <p style="text-align: justify">Where Φ<sub>p</sub> is the proton (or pion) fluence [cm<sup>-2</sup>] and (dE/dx)<sub>min</sub> are the values listed in this <a href="https://ps-irrad.web.cern.ch/assets/doc/info/atomic%20and%20nuclear%20properties%20of%20materials.pdf" style=" text-decoration: underline;">table</a> [MeV·cm<sup>2</sup>/g] for various materials and compounds. </p>
               <p style="text-align: justify"> For further information please read this publicaton <a href="https://doi.org/10.1109/TNS.2018.2829864" style=" text-decoration: underline;">https://doi.org/10.1109/TNS.2018.2829864</a></p>
            </p>
    </div>
    <div class="ui segment">
         <h3 class = "ui center aligned header">TID (Gy) vs. TID (rad)</h3>
         <p style="text-align: justify">Please, find an online converter in this <a href="https://www.unitconverters.net/radiation-absorbed-dose/gray-to-rad.htm" style=" text-decoration: underline;">link</a></p>
    </div>
</div>
{% endblock %}

samples_manager/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class= "ui center aligned raised segment">
      <p>Welcome to ITA Data Manager, the all-in-one data management tool for the registration, supervision and follow up of ITA experiments. If you are not member of irrad-ps-users e-group, please <a  target="_blank" style="text-decoration: underline;" href="https://e-groups.cern.ch/e-groups/Egroup.do?egroupId=10115020">subscribe</a> there before signing in.</p>
                      <a target="_blank" style="text-decoration: underline;" href="https://e-groups.cern.ch/e-groups/Egroup.do?egroupId=10115020" title="Subscribe to irrad-ps-users e-group">
                        <button type="button" class="massive ui positive compact icon button">
                          <i class="users icon"></i> Subscribe in e-group
                        </button>  
                      </a>
                      <a href='{% url 'samples_manager:index' %}' title="Sign in">
                        <button type="button" class="massive ui yellow compact icon button">
                          <i class="sign in alternate icon"></i> Sign In
                        </button>  
                      </a>
  </div>


 <!-- THE MODAL WE WILL BE USING -->
   <div class="modal fade in" id="modal-experiment">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
    </div>
  <div class="modal fade in" id="modal-sample">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
  </div>
  <div class="modal fade in" id="modal-user">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
{% endblock %}

samples_manager/templates/terms_conditions.html
{% extends 'base.html' %}

{% block content %}
<div class= "ui center aligned segment" id="main_panel">
  <h2>General Terms</h2>
</div>
<div class= "ui segment" id = "regulations">
        <p>The access to the IRRAD area is given once per week (Wednesday morning from 9:00 to 12:00) to allow the installation/removal of large samples and experimental test setups.
           Samples installation on the irradiation tables requires dedicated support frames provided by the users.  </p>
        <p>Depending on the samples nature, the preparation of an irradiation permit (PRP17) may be required before the irradiation begins (<a href="https://edms.cern.ch/document/1717433"> https://edms.cern.ch/document/1717433 </a>). This safety procedure may require several weeks to be completed.</p>
        <p>Users are requested to be present at CERN in case their samples have to be handled before and/or after irradiation (e.g. to prepare them for shipping outside CERN).</p>
        <p>Installation/removal of complex experiments on the irradiation tables require the presence of a minimum of two people from the users’ team on site.
           Users are responsible for obtaining the required safety training ranks, access rights, personal (DIS) and operational dosimeters (DMC), as well as all required Personal Protective Equipment (safety shoes, helmet) before the scheduled access slot. All requirements to be able to access the IRRAD irradiation area are available <a href="https://ps-irrad.web.cern.ch/ps-irrad/index.php?link=access.html" style=" text-decoration: underline;">here</a></p>
        <p>The IRRAD facility is supported through the AIDA-2020 Transnational Access (TA) program.<p>
          <ol class="ui list">
            <li>All accepted user teams in 2018 must fill in an <a href="http://aida2020.web.cern.ch/content/transnational-access " style=" text-decoration: underline;">AIDA-2020 TA form </a> and have the possibility to request a financial support for their irradiation experiment, if needed.
            In case financial support is required, please contact in advance the AIDA-2020 TA facility Coordinator for IRRAD (Michael.Moll@cern.ch).</li>
            <li>Publications (journal/conference papers, notes, reports, etc.) from the user teams with results related to the AIDA-2020 TA experiments in IRRAD should include the <a href="http://aida2020.web.cern.ch/science/publications" style=" text-decoration: underline;"> AIDA-2020 acknowledgement text</a></li>
            <li>More details about the AIDA-2020 Transnational Access program are available <a href="http://aida2020.web.cern.ch/content/transnational-access" style=" text-decoration: underline;">here</a></li>
          </ol>
        </ol>
  </div>
{% endblock %}