samples_manager/urls.py
from django.conf.urls import url, include

from django.views.generic import TemplateView
from . import views, user_views, experiment_views, sample_views, dosimeter_views, irradiation_views, compound_views



urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<experiment_id>[0-9]+)/experiment/$', experiment_views.experiment_details, name='experiment_details'),
    url(r'^logged_user/$',  user_views.view_user, name='view_user'),
    url(r'^experiments/$', experiment_views.experiments_list, name='experiments_list'),
    url(r'^user/(?P<pk>\d+)/experiments/$', experiment_views.admin_experiments_user_view, name='admin_experiments_user_view'),
    url(r'^admin/experiments/$', experiment_views.admin_experiments_list, name='admin_experiments_list'),
    url(r'^experiments/history/$', experiment_views.admin_experiments_list, name='experiments_history'),
    url(r'^experiment/new/$', experiment_views.experiment_new, name='experiment_new'),
    url(r'^experiments/(?P<pk>\d+)/update/$', experiment_views.experiment_update, name='experiment_update'),
    url(r'^experiments/(?P<pk>\d+)/delete/$', experiment_views.experiment_delete, name='experiment_delete'),
    url(r'^experiments/(?P<pk>\d+)/clone/$', experiment_views.experiment_clone, name='experiment_clone'),
    url(r'^experiments/(?P<pk>\d+)/validate/$', experiment_views.experiment_validate, name='experiment_validate'),
    url(r'^experiments/(?P<pk>\d+)/status/$', experiment_views.experiment_status_update, name='experiment_status_update'),
    url(r'^experiments/(?P<pk>\d+)/print/$', views.print_experiment_view, name='print_experiment_view'),
    url(r'^users/$',  user_views.users_list, name='users_list'),
    url(r'^experiment/(?P<experiment_id>\d+)/users/$',  user_views.experiment_users_list, name='experiment_users_list'),
    url(r'^experiment/(?P<experiment_id>\d+)/user/new/$',  user_views.user_new, name='user_new'),
    url(r'^user/new/$',  user_views.admin_user_new, name='admin_user_new'),
    url(r'^experiment/(?P<experiment_id>\d+)/user/(?P<pk>\d+)/update/$', user_views.user_update, name='user_update'),
    url(r'^experiment/(?P<experiment_id>\d+)/user/(?P<pk>\d+)/delete/$', user_views.user_delete_from_experiment, name='user_delete_from_experiment'),
    url(r'^user/(?P<pk>\d+)/delete/$', user_views.admin_user_delete, name='admin_user_delete'),
    url(r'^user/(?P<pk>\d+)/update/$', user_views.admin_user_update, name='admin_user_update'),
    url(r'^regulations/$',views.regulations, name='regulations'),
    url(r'^fluence_conversion/$',views.fluence_conversion, name='fluence_conversion'),
    url(r'^experiment/(?P<experiment_id>\d+)/samples/$', sample_views.experiment_samples_list, name='experiment_samples_list'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/new/$', sample_views.sample_new, name='sample_new'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/update/$', sample_views.sample_update, name='sample_update'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/clone/$', sample_views.sample_clone, name='sample_clone'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/delete/$', sample_views.sample_delete, name='sample_delete'),
    url(r'^experiment/(?P<experiment_id>\d+)/samples/move_samples/$', sample_views.move_samples, name='move_samples'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/print/label/$', views.print_sample_label_view, name='print_sample_label_view'),
    url(r'^experiment/(?P<experiment_id>\d+)/sample/(?P<pk>\d+)/print/$', views.print_sample_view, name='print_sample_view'),
    url(r'^dosimeters/$',  dosimeter_views.dosimeters_list, name='dosimeters_list'),
    url(r'^dosimeter/new/$',  dosimeter_views.dosimeter_new, name='dosimeter_new'),
    url(r'^dosimeter/(?P<pk>\d+)/update/$',  dosimeter_views.dosimeter_update, name='dosimeter_update'),
    url(r'^dosimeter/(?P<pk>\d+)/clone/$',  dosimeter_views.dosimeter_clone, name='dosimeter_clone'),
    url(r'^dosimeter/(?P<pk>\d+)/delete/$',  dosimeter_views.dosimeter_delete, name='dosimeter_delete'),
    url(r'^dosimeter/(?P<pk>\d+)/print/label/$', views.print_dosimeter_label_view, name='print_dosimeter_label_view'),
    url(r'^experiment/(?P<experiment_id>\d+)/dosimeter/assign/$', dosimeter_views.assign_dosimeters, name='assign_dosimeters'),
    url(r'^dosimeters/generate/ids/$', dosimeter_views.generate_dos_ids, name='generate_dos_ids'),
    url(r'^irradiations/$', irradiation_views.irradiations, name='irradiations'),
    url(r'^search_irradiations/$', views.search_irradiations, name='search_irradiations'),
    url(r'^search/experiment/(?P<experiment_id>\d+)/sample$', sample_views.search_samples, name='search_samples'),
    url(r'^search/experiments/user$', views.search_experiments_user, name='search_experiments_user'),
    url(r'^search/admin/experiments/$', views.search_experiments_admin, name='search_experiments_admin'),
    url(r'^search/experiment/(?P<experiment_id>\d+)/users/$', views.search_experiment_users, name='search_experiment_users'),
    url(r'^search/admin/users/$', views.search_users_admin, name='search_users_admin'),
    url(r'^search/dosimeters/$', views.search_dosimeters, name='search_dosimeters'),
    url(r'^admin/compound/new/$', compound_views.admin_compound_new, name='admin_compound_new'),
    url(r'^admin/compound/(?P<pk>\d+)/update/$', compound_views.admin_compound_update, name='admin_compound_update'),
    url(r'^admin/compound/(?P<pk>\d+)/delete/$', compound_views.admin_compound_delete, name='admin_compound_delete'),
    url(r'^experiment/(?P<experiment_id>\d+)/compound/new/$', compound_views.compound_new, name='compound_new'),
    url(r'^compounds/$', compound_views.compounds_list, name='compounds_list'),
    url(r'^experiment/(?P<experiment_id>\d+)/assign_set_ids/$', sample_views.assign_set_ids, name='assign_set_ids'),
    url(r'^experiment/(?P<experiment_id>\d+)/archive/samples/$', sample_views.archive_experiment_samples, name='archive_experiment_samples'),
    url(r'^experiment/(?P<experiment_id>\d+)/new/irradiation/$', irradiation_views.new_group_irradiation, name='new_group_irradiation'),
    url(r'^irradiation/new/$', irradiation_views.irradiation_new, name='irradiation_new'),
    url(r'^irradiation/(?P<pk>\d+)/update/$', irradiation_views.irradiation_update, name='irradiation_update'),
    url(r'^irradiation/(?P<pk>\d+)/delete/$', irradiation_views.irradiation_delete, name='irradiation_delete'),
    url(r'^irradiation/(?P<pk>\d+)/status/update/$', irradiation_views.irradiation_status_update, name='irradiation_status_update'),
    url(r'^register/preferences/$', views.register_preferences, name='register_preferences'),
    url(r'^change/experiment/(?P<pk>\d+)/visibility/$', experiment_views.change_experiment_visibility, name='change_experiment_visibility'),
    url(r'^change/experiment/(?P<pk>\d+)/visibility/on/$', experiment_views.change_experiment_visibility, name='change_experiment_visibility_on'),
    url(r'^change/experiment/(?P<pk>\d+)/visibility/off/$', experiment_views.change_experiment_visibility, name='change_experiment_visibility_off'),
    url(r'^get/sec/$', views.get_sec, name='get_sec'),
    url(r'^admin/dosimetry/results/$', irradiation_views.admin_dosimetry_results, name='admin_dosimetry_results'),
    url(r'^sample/(?P<sample_id>\d+)/dosimetry/results/$', irradiation_views.dosimetry_results, name='dosimetry_results'),
    url(r'^irradiation/beam/change/$', views.in_beam_change, name='in_beam_change'),
    url(r'^select_table/$', views.select_table, name='select_table'),
    url(r'^experiment/(?P<pk>\d+)/comment/$', experiment_views.experiment_comment_update, name='experiment_comment_update'),
    url(r'^read/(?P<pk>\d+)/trec$', views.read_sample_trec, name='read_sample_trec'),
    url(r'^samples/$',sample_views.admin_samples_list, name='admin_samples_list'),
    ]

test-irrad-management-page/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    # Examples:
    # url(r'^$', 'test2_samples_manager.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^samples_manager/', include('samples_manager.urls', namespace="samples_manager")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^terms_conditions/', TemplateView.as_view(template_name='terms_conditions.html'), name='terms_conditions'),
    url(r'^fluence_conversion/', TemplateView.as_view(template_name='fluence_conversion.html'), name='fluence_conversion'),
]

samples_manager/templates/samples_manager/admin_experiments_list.html
{% extends 'samples_manager/base.html' %}
{% block content %}


 <!-- THE MODAL WE WILL BE USING -->
  <div class="ui modal" id="modal-experiment">
     <i class="close icon"></i>
     <div class="scrolling content">
      </div>
  </div>
  
<div class= "ui center aligned raised segment">
     <h2 >Irradiation Experiments</h2>
     <div class= "ui grid">
        <div class="three wide column">
                    <button type="button" class="ui left floated grey button" onclick="goBack()" title='Back'>
                        <i class="angle left icon"></i>Back
                    </button>
        </div>
        <div class="ten wide column">
            <form style="text-align: center; display: block" name="search_form" method="GET" action="{% url 'samples_manager:search_experiments_admin'%}"> 
                <div class="ui fluid right action icon input">
                    <input title="Search irradiation title or status"   id="search_box" type="text" name="search_box"  placeholder="Search..." >
                    <button title="Search irradiation title or status" class="ui icon green button" id="search_submit" type="submit"><i class="search icon"></i></button>
                </div>
            </form>
        </div>
        <div class="three wide column">
            <button type="button"
                        data-target = "#modal-experiment"
                        class="ui blue right floated button js-create-experiment"
                        title='Register new irradiation experiment'
                        data-url="{% url 'samples_manager:experiment_new' %}">
                        <i class="plus icon"></i>New Experiment
            </button> 
        </div>
    </div>
    <div class="sixteen wide column" style='overflow-x:scroll;'>
        <table class="ui center aligned sortable celled table" id="data-table">
        			{% include 'samples_manager/partial_admin_experiments_list.html' %}



        </table>
    </div>
</div>

{% endblock %}

samples_manager/templates/samples_manager/admin_samples_list.html
{% extends 'samples_manager/base.html' %}
{% block content %}
{% load staticfiles %}
{% load widget_tweaks %}

<!-- THE MODAL WE WILL BE USING -->
<div class="ui modal" id="modal-irradiation">
    <i class="close icon"></i>
    <div class="scrolling content">
    </div>
</div>

<div class="ui modal" id="modal-sample">
    <i class="close icon"></i>
    <div class="scrolling content">
    </div>
</div>

<div class="ui modal" id="modal-compound">
    <i class="close icon"></i>
    <div class="scrolling content">
    </div>
</div>
 
<div class= "ui center aligned raised segment">
    <h2>{{experiment.title}} samples</h2>
        <div class= "ui grid segment"  id= "unchecked_segment">
        <div class="three wide column">
                    <button type="button" class="ui left floated grey button"  onclick="goBack()" title='Back'>
                        <i class="angle left icon"></i>Back
                    </button>
        </div>
        
        <div class="ten wide column">
            <form style="text-align: center; display: block" name="search_form" method="GET" action="{% url 'samples_manager:search_samples' experiment.id%}"> 
                <div class="ui fluid right action icon input">
                    <input title="Search irradiation title or status"   id="search_box" type="text" name="search_box"  placeholder="Search..." >
                    <button title="Search irradiation title or status" class="ui icon green button" id="search_submit" type="submit"><i class="search icon"></i></button>
                </div>
            </form>
        </div>
        <div class="three wide column">
            <button type="button"
                        id = "new_sample"
                        data-target = "#modal-sample"
                        class="ui blue button js-create-sample"
                        title='Register new sample'
                        data-url="{% url 'samples_manager:sample_new' experiment.id %}">
                        <i class="plus icon"></i> New Sample
                </button>  
        </div>
    </div>
     
        <form method="post" id='move_samples'  action="">
        {% csrf_token %} 
        <div class= "ui grid segment" id= "checked_segment" style = "display: none">
        <div class="three wide column">
            <button  type="submit"
                        id = "assign_ids"
                        class="ui violet button"
                        data-url="{% url 'samples_manager:assign_set_ids' experiment.id %}">
                        <i class="tags icon"></i> Assign SET ID
            </button>
        </div>
        <div class="three wide column">
            <button  type="submit"
                    id = "print_samples"
                    class="ui orange button">
                    <i class="barcode icon"></i> Print labels
            </button>  
        </div>
        <div class="three wide column">
                <button  type="button"
                    id = "new_group_irradiation"
                    class="ui negative button"
                    data-url="{% url 'samples_manager:new_group_irradiation' experiment.id %}">
                    <i class="bolt icon"></i> New irradiation 
                </button>   
        </div>
        <div class="seven wide column">
            <div class="ui right action input">
                <select class="form-control" id="id_experiments" name="new_experiment">
                                    <option value="" selected="selected">Move samples to another experiment</option>
                                    {% for experiment in experiments %}
                                        <option value="{{experiment.id}}">{{experiment.title}}</option>
                                    {% endfor %}
                </select>
                <button type="submit"
                                    id = "change_experiment"
                                    data-url="{% url 'samples_manager:move_samples' experiment.id %}"
                                    class="ui positive button">
                                    <i class="check icon"></i>
                </button>
            </div>
        </div>
    </div>




    <div class="sixteen wide column" style='overflow-x:scroll;'>
        <div class="ui toggle checkbox" id= "experiment_visibility_checkbox">
           {% include 'samples_manager/experiment_visibility.html' %}
        </div>
        <table class="ui center aligned sortable celled table" id="data-table">
                            <thead>
                                <tr>
                                <th class="sorttable_nosort"><input name="select_all" value="1" id="samples-select-all" type="checkbox"/></th>
                                <th>Last<br>update</th>
                                <th>ID</th>    
                                <th>Name</th>
                                <th>Category</th>
                                <th>Requested<br>fluence</th>
                                <th>Radiation / Nu. Coll. / Nu. Int.<br>Length Occupancy (%)</th>
                                <th>Last<br>updated by</th>
                                <th class="sorttable_nosort">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% include 'samples_manager/partial_samples_list.html' %}
                            </tbody>
        </table>
        <p><a href="{% url 'samples_manager:archive_experiment_samples' experiment.id%}">Archive</a></p>
    </div>
 </div>
</form>
{% endblock %}

samples_manager/templates/samples_manager/partial_experiment_create.html
<meta charset="UTF-8"> 
{% load staticfiles %}
{% load widget_tweaks %}
<form method="post" action="{% url 'samples_manager:experiment_new' %}" class="ui form js-experiment-create-form" novalidate>
{% csrf_token %}
<div class="ui centered grid container">
    <div class="ui text container">
      <div class="three ui buttons center aligned grid container" style="margin:20px;">
        <div class=" ui  big basic blue button" id="step1S">
          <div class="content ">Experiment Details</div>
        </div>
        <button class=" ui  big disabled blue basic button" id="step2S">
             <div class="content">Samples Details</div>
             </button>
        <button class=" disabled ui big blue basic button" id="step3S">
             <div class="content">Additional Comments</div>
             </button>
      </div>

      <div id="step1">
        <div class="ui center aligned segment container ">
          <div class="ui centered header">
            <h3>Experiment Details</h3>
          </div>
                {% for field in form1 %}
                    <div  class="field form-group{% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                    <span class="ui  pointing  basic label">{{error }}</span>
                {% endfor %}
                    </div>
                {% endfor %}
            <div class="two ui buttons actions">
              <button  type="button"  class="ui deny medium button">Cancel</button>
              <button type="button" class="ui  inverted blue  medium button next1">Next</button>
            </div>
        </div>
      </div>

      <div id="step2">
        <div class="ui center aligned segment container ">
          <div class="ui centered header">
            <h3>Samples Details</h3>
          </div>
           {% for field in form2 %}
                    <div class="field form-group{% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% render_field field class="form-control" %}
                {% for error in field.errors %}
                    <span class="ui  pointing  basic label">{{error }}</span>
                {% endfor %}
                    </div>
            {% endfor %}
            <div id = "passive_standard_category" style="display:none">
                        <p>Irradiation area:</p>
                        <div class="fields">
                            {% for field in passive_standard_categories_form %}
                                <div class="seven wide field form-group{% if field.errors %} has-error{% endif %}">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {% render_field field class="form-control" %}
                            {% for error in field.errors %}
                                <span class="ui  pointing  basic label">{{error }}</span>
                            {% endfor %}
                                </div>
                            {% endfor %}
                        </div>
            </div>
            <div id = "passive_custom_category" >
                    {% for field in passive_custom_categories_form %}
                        <div class="field form-group{% if field.errors %} has-error{% endif %}">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                        <span class="ui  pointing  basic label">{{error }}</span>
                    {% endfor %}
                        </div>
                    {% endfor %}
            </div>
            <div id = "active_category" >
                    {% for field in active_categories_form %}
                        <div class="field form-group{% if field.errors %} has-error{% endif %}">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% render_field field class="form-control" %}
                    {% for error in field.errors %}
                        <span class="ui  pointing  basic label">{{error }}</span>
                    {% endfor %}
                        </div>
                    {% endfor %}
            </div>
            <table  class="ui celled table formset_table">
                        {{ fluence_formset.management_form }}
                        {% for form in fluence_formset.forms %}
                        {% if forloop.first %}
                                <thead>
                                <tr>
                                    <th>Requested fluence * (<a target='_blank' style="color: #333; text-decoration:underline" title="Conversion to protons/cm²" href="{% url 'samples_manager:fluence_conversion' %}"> protons/cm²</a>)
                                    <a target='_blank' href="{% url 'samples_manager:fluence_conversion' %}"><i class="info circle icon"></i></a></th>
                                    <th>Delete</th>
                                </tr>
                                </thead>
                            {%endif %}
                            <tr class="{% cycle row1 row2 %} formset_row">
                                {% for field in form.visible_fields %}
                                    <td>
                                        {# Include the hidden fields in the form #}
                                        {% if forloop.first %}
                                            {% for hidden in form.hidden_fields %}
                                                {{ hidden }}
                                            {% endfor %}
                                        {% endif %}
                                        {{ field }}
                                        {% for error in field.errors %}
                                            <span class="ui  pointing  basic label">{{error}}</span>
                                        {% endfor %}
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                    <table  class="ui celled table formset_table">
                        {{ material_formset.management_form }}
                        {% for form in material_formset.forms %}
                            {% if forloop.first %}
                                <thead>
                                <tr>
                                    {% for field in form.visible_fields %}
                                        <th>{{ field.label|capfirst }}</th>
                                    {% endfor %}
                                </tr>
                                </thead>
                            {% endif %}
                            <tr class="{% cycle row1 row2 %} material_formset_row">
                                {% for field in form.visible_fields %}
                                    <td>
                                        {# Include the hidden fields in the form #}
                                        {% if forloop.first %}
                                            {% for hidden in form.hidden_fields %}
                                                {{ hidden }}
                                            {% endfor %}
                                        {% endif %}
                                        {{ field }}
                                        {% for error in field.errors %}
                                            <span class="ui  pointing  basic label">{{error}}</span>
                                        {% endfor %}
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
            <div class="two ui buttons actions">
              <button  type="button" class="ui  inverted blue  medium button prev1">Previous</button>
              <button  type="button"  class="ui  inverted blue  medium button next2">Next</button>
            </div>
        </div>
      </div>


      <div id="step3">
        <div class="ui center aligned  segment container ">
          <div class="ui centered header">
            <h3>Additional Comments</h3>
          </div>
          {% for field in form3 %}
                        <div class="field form-group{% if field.errors %} has-error{% endif %}">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {% render_field field class="form-control" %}
                        {% for error in field.errors %}
                            <span class="ui  pointing  basic label">{{error }}</span>
                        {% endfor %}
                            </div>
            {% endfor %}
            <div class="two ui buttons actions">
              <button  type="button" class="ui inverted blue medium button prev2">Previous</button>
              <button  type="submit" id="experiment_submit" class="ui positive medium button submit">Submit</button>
            </div>
        </div>
      </div>
    </div>
  </div>
</form>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/steps.js' %}"></script>
  <script>
     if($("#id_category").val() === 'Passive Standard'){
                $('#passive_custom_category').hide();
                $('#active_category').hide();
                $('#passive_standard_category').show();

            }
        else if ($("#id_category").val() === 'Passive Custom') {
                $('#passive_standard_category').hide();
                $('#active_category').hide();
                $('#passive_custom_category').show();
            }
        else if ($("#id_category").val() === 'Active'){
                $('#passive_standard_category').hide();
                $('#passive_custom_category').hide();
                $('#active_category').show();
        }else{
                $('#passive_standard_category').hide();
                $('#passive_custom_category').hide();
                $('#active_category').hide();
        }

    $( "#id_category" ).on( "change", function() {
        if($("#id_category").val() === 'Passive Standard'){
                $('#passive_custom_category').hide();
                $('#active_category').hide();
                $('#passive_standard_category').show();

            }
        else if ($("#id_category").val() === 'Passive Custom') {
                $('#passive_standard_category').hide();
                $('#active_category').hide();
                $('#passive_custom_category').show();
            }
        else if ($("#id_category").val() === 'Active'){
                $('#passive_standard_category').hide();
                $('#passive_custom_category').hide();
                $('#active_category').show();
        }else{
                $('#passive_standard_category').hide();
                $('#passive_custom_category').hide();
                $('#active_category').hide();
        }
    });
        $('.formset_row').formset({
            addText: 'Add',
            deleteText: '×',
            prefix: 'reqfluences_set'
        });
        $('.material_formset_row').formset({
            addText: 'Add',
            deleteText: '×',
            prefix: 'materials_set'
        });
    $( function() {
        $( "#id_availability" ).datepicker({ dateFormat: 'dd/mm/yy' });
    } );
  </script>

samples_manager/templates/samples_manager/partial_samples_list.html
{% for sample_data in samples_data %}
  <tr>
    <td><input type="checkbox" class="chkbox" id="{{sample.id}}" name="checks[]" value="{{sample_data.sample.set_id}}</font></b><br/>{{sample_data.sample_category}}<br/>{{sample_data.sample.req_fluence}}<br/>{{experiment.responsible.surname}}<br/>{{sample_data.sample.name}}"></td>
    <td>{{ sample_data.sample.updated_at|date:"d/m/Y"}}</td>
    {%if sample_data.sample.set_id %}
    <td>{{sample_data.sample.set_id}}</td>
    {%else %}
    <td>Not assigned</td>
    {%endif%}
    <td>{{ sample_data.sample.name }}</td>
    <td>{{ sample_data.sample.category}}</td>
    <td>{{ sample_data.sample.req_fluence}}</td>
    <td>{{ sample_data.occupancy.radiation_length_occupancy}} / {{ sample_data.occupancy.nu_coll_length_occupancy}} / {{ sample_data.occupancy.nu_int_length_occupancy}}</td>
    <td>{{ sample_data.sample.updated_by}}</td>
    <td>
        <button type="button"
                class="mini ui yellow icon button js-update-sample"
                data-url="{%  url 'samples_manager:sample_update' experiment.id sample_data.sample.id %}"
                title='View or Edit sample'>
              <i class="pencil icon"></i>Edit
        </button>
        {% if experiment.status != 'Completed'%}
        <button type="button"
                class="mini ui blue icon button js-clone-sample"
                data-url="{%url 'samples_manager:sample_clone' experiment.id sample_data.sample.id %}"
                title='Clone sample'>
          <i class="clone icon"></i>Clone
        </button>
        {%else%}
        <a href="{% url 'samples_manager:dosimetry_results' sample_data.sample.id  %}">  
          <button type="button"
                  class="mini ui green icon button"
                  title='Dosimetry results'>
            <i class="book icon"></i>Results
          </button>
        </a>
        {% endif %}
        <button type="button"
                  class="mini ui grey icon dropdown link button allowed_dropdown"
                  title='More options'>
                 <i class="ellipsis vertical icon"></i>More
                 <div class="menu">
                      <a  href="{% url 'samples_manager:print_sample_view' experiment.id sample_data.sample.id  %}" class="item"><b>Print</b></a>
                      <a data-url="{% url 'samples_manager:print_sample_label_view' experiment.id sample_data.sample.id %}" class="js-print-sample-label item"><b>Print Label</b></a>
                      {% if experiment.status != 'Completed'%}
                      <a data-url="{% url 'samples_manager:sample_delete' experiment.id sample_data.sample.id %}" class="item js-delete-sample"><b>Delete</b></a>
                      {% endif %}
                      {% if logged_user.role == 'Admin'%}
                        <a href="{% url 'samples_manager:read_sample_trec' sample_data.sample.id  %}" class="item"><b>TREC</b></a>
                      {% endif %}
                  </div>
        </button>
    </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="10" class="text-center">There are no samples</td>
  </tr>
{% endfor %}
<script>
            $('.allowed_dropdown')
            .dropdown();
            function goBack() {
                window.history.back();
            }
    </script>